#ifndef ERROR_H
#define ERROR_H

typedef enum
{
    DARCH_ERROR_BAD_ARGUMENTS = 1,
    DARCH_ERROR_FILE_ACCESS = 2,
    DARCH_ERROR_BAD_MAGIC_VALUE = 3,
    DARCH_ERROR_INACCESSIBLE_FS_OBJECT = 4,
    DARCH_ERROR_OUTPUT_DIRECTORY_CREATION_FAILURE = 5,
	DARCH_ERROR_ALREADY_EXISTS = 6,

    DARCH_ERROR_WTF = 0xFFFFFF
} DARCH_ERROR;

#endif