#ifndef ERROR_H
#define ERROR_H

typedef enum
{
    ERROR_BAD_ARGUMENTS = 1,
    ERROR_FILE_ACCESS = 2,
    ERROR_BAD_MAGIC_VALUE = 3,
    ERROR_INACCESSIBLE_FS_OBJECT = 4,
    ERROR_OUTPUT_DIRECTORY_CREATION_FAILURE = 5,

    ERROR_WTF = 0xFFFFFF
} ERROR;

#endif